### PR TITLE
Add missing pycrypto dependency

### PR DESCRIPTION
**Pull request by patrickgombert**
Fabric seems to have a dependency on pycrypto which went unspecified

### CODE REVIEW

**Comment by stantonk** [comment]
@patrickgombert thanks! do you mind bumping the version to 0.6.1 so this will work when people install it? I have yet to push a version to the central pypi, I'll push it when this gets updated! see:

https://github.com/sproutsocial/mendel/blob/master/mendel/version.py

**Comment by patrickgombert** [comment]
@stantonk I bumped the version

**Comment by stantonk** [comment]
@patrickgombert ah i don't have write access anymore to merge... :( can you ask someone about that?

**Comment by alanboyce** [comment]
@stantonk you should have write access again, sorry about that.

**Pull request merged**
