### PR TITLE
send slack messges when the deploy fails

### PR DESCRIPTION
**Pull request by brianc-sprout**
When a deploy fails, we should also notify the slack channel if it is configured.

### CODE REVIEW

**Comment by brianc-sprout** [comment]
I also really have no idea how to test this before a deploy, @Ibracadabra05 is there an easy way to test?

**Comment by Ibracadabra05** [comment]
@brianc-sprout By running tox within the root dir

**Comment by Ibracadabra05** [comment]
@brianc-sprout you can also create a new virtual environment within this repo, and run python `setup.py` install. And try deploying a service using said virtual env

**Comment by brianc-sprout** [comment]
Okay, `tox` now passes and I tried the good and error paths locally, and the slack messages get sent fine

**Pull request merged**
