### PR TITLE
DATAINJ-573 handle multiple python distributions in dist directory; update docs

### PR DESCRIPTION
**Pull request by mdowell12**
After deploying a python service with mendel multiple times, you end up with a few distribution files in your local `dist` directory.  Mendel then complains when it tries to get the name of your newest distribution on subsequent deploys, because it currently assumes that there will be only one `*.tar.gz` file in your `dist` directory.  This update makes mendel look for the most recently updated `*.tar.gz` file in the `dist` directory when deploying python services.

I also updated some documentation to reflect the fact that we now support python builds.

### CODE REVIEW

**Comment by mdowell12** [comment]
Sorry for the whitespace diffs.  Here's a link without them: https://github.com/sproutsocial/mendel/pull/16/files?w=1

**Comment by stantonk** [comment]
@mdowell12 mendel only supports java services...?

**Comment by mdowell12** [comment]
@stantonk not sure of the history behind this, but we've certainly been using it in [facebook-insights](https://github.com/sproutsocial/facebook-insights/blob/master/mendel.yml) for a month or so.

**Comment by dnfehren** [comment]
I added python a long time back - but there were some issues (I think this was one of them) that prevented wider adoption.

**Comment by mdowell12** [comment]
Thanks @dnfehren. I also uncovered an issue trying to rollback a deploy (outlined here: https://sprout.atlassian.net/browse/DATAINJ-573).  I may be able to tackle that at some point in the coming weeks, but wanted to make you aware.

**Pull request merged**
