### PR TITLE
Only send slack notifications for local builds and (local + remote) deployments

### PR DESCRIPTION
**Pull request by Ibracadabra05**
The `_track_event()` function notifies `graphite`, `slack`, & an `"external rest api endpoint"`. We don't really care about non-deploy & non-rollback events in graphite. And posting to slack for every single event can get a little extraneous.

### CODE REVIEW

**Comment by Ibracadabra05** [comment]
This can be extraneous for services that are deployed to multiple servers...
screen shot 2018-10-05 at 3 11 24 pm

**Comment by Ibracadabra05** [comment]
Unless I am missing something and y'all would be fine having this?

**Comment by brianc-sprout** [comment]
you went from too much, to not doing a single slack call. I think just leaving it in deploy is probably enough

**Comment by Ibracadabra05** [comment]
Lol it is doing slack calls during deploys and rollbacks. Just not for
every single stage except builds when they do happen locally

**Pull request merged**
